.Au John Kaul
.Dd Feb 07 2025
.Dt sysconf.7
.Os
.Pp
.Sh NAME
.Nm sysconf
.Pp
.Sh SYNOPSIS
sysconf -f configfile
.Pp
sysconf -f configfile [-n] [key]
.Pp
sysconf -f configfile [-n] [key=value]
.Pp
sysconf -f configfile [-n] [key+=value]
.Pp
sysconf -f configfile [-n] [key-=value]
.Pp
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl f
Configuration file
.It Fl n
Display "key" as well when retrieving a variable. The default method is to only display a key's value but this option makes the return show both the key and the value.
.El
.Pp
.Sh DESCRIPTION
This utility will print and/or change a configuration value stored in a configuration file formatted in the typical key/value syntax with zero dependencies on external libraries or tools.
.Pp
By design this utility does not have any flags to specify actions to preform different actions, instead this utility will determine what to do, or not to do, based on the arguments given and what is currently in the config file. See the examples below. This utility will also try to determine the syntax of the key/value pair by reading the configuration file (-i.e. it will try to determine if the value needs quotes or a termination character and either spaces or an equal sign or colon separation character).
.Pp
This utility can also add and subtract values to a key with '+=' and '-='.
.Pp
Configuration file syntaxes this utility can parse:
.Bd -literal -offset indent
    key=value
    key = value;
    key.subkey = value;
    key="value"
    key value
    key value;
    key:"value"
    key = "value1 value2";
    etc.
.Ed
.Pp
.Sy NOTE
Some keys or values in configuration files can contain special characters like dollar signs ($). To pass these characters to this utility, the dollar sign must be escaped with a slash (\\) or the string can be surrounded with single quotes (').
.Pp
If the configuration file does not already contain the key=value entry this utility will add the entry in the following format.
.Pp
.Bd -literal -offset indent
key = value
.Ed
.Pp
This utility also does not allow for duplicate key/values in the config file, and will not add an entry if it already exists.
.Pp
.Sh EXAMPLES
.Pp
.Em LIST ALL VALUE(S)
.Pp
.Pp
To list off (pretty print) the key/values in a config file just call the program with no arguments. However, the way this program parses the key/value strings may result in slightly odd looking results so you should not try to use this utility to remove duplicate key/values.
.Bd -literal -offset indent
    % syconf -f /path/config.file
.Ed
.Pp
.Pp
.Em GET A VALUE
.Pp
To retrieve the value from a key in a file call this program with just the key to search for. This utility will only return the value(s) for the given key to better support usage from within a script.
.Bd -literal -offset indent
    % sysconf -f /path/config.file key
.Ed
.Pp
If there is a need to produce the key as well as the value in the output of a 'get a value' operation, the `-n` switch can be used.
.Bd -literal -offset indent
    % sysconf -f /path/config.file -n key
.Ed
.Pp
.Em CHANGE VALUE(S)
.Pp
To change a value associated with a key use the equal (=) sign. A change will only be made if the value does not match what is currently in the config file -i.e., if the value to be assigned is already the same as it is in the config file, no change is made.
.Bd -literal -offset indent
    % sysconf -f /path/config.file key=value
.Ed
.Pp
To add to a value associated with a key use a plus-equal (+=). A change will only be added if the value does not already exist in the config value string -i.e., if the value to be assigned is already part of the config file value, no change is made.
.Bd -literal -offset indent
    % sysconf -f /path/config.file key+=value
.Ed
.Pp
To remove a value associated with a key use a minus-equal (-=). A change will only be made if the value exists in the config file value string.
.Bd -literal -offset indent
    % sysconf -f /path/config.file key-=value
.Ed
.Pp
.Em ESCAPING CHARS
.Pp
To use a dollar sign in a key, escape it.
.Bd -literal -offset indent
    % sysconf -f /path/config.file \\$key
.Ed
.Pp
or use single quotes to surround the string.
.Bd -literal -offset indent
    % sysconf -f /path/config.file '$key'
.Ed
.Pp
.Sh HISTORY
Created for my personal use.
.Pp
.Sh AUTHOR
John Kaul
