.Au John Kaul
.Dd Feb 07 2025
.Dt sysconf.7
.Os
.Pp
.Sh  NAME
sysconf
.Pp
.Sh  SYNOPSIS
sysconf
.Op Fl f Ar configfile
.Op  Ar key=value
.Pp
.Sh  OPTIONS
.Bl -tag -width Ds
.It Fl f
Configuration file
.Pp
.El
.Pp
.Sh  DESCRIPTION
This utility will print/change a configuration value stored in a configuration file formatted in the typical key/value syntax.
.Pp
By design this utility does not have any flags to specify actions to preform different actions, instead this utility will determine what to do based on the arguments given. See the examples below. This utility will also try to determine the syntax of the key/value pair by reading the configuration file (-i.e. it will try to determine if the value needs quotes or a temination character and either spaces or an equal sign or colon seperation character).
.Pp
Configuration file syntaxes this utility can parse:
.Bd -literal -offset indent
    key=value
    key = value;
    key.subkey = value;
    key="value"
    key value
    key value;
    key:"value"
    key = "value1 value2";
    etc.
.Ed
.Pp
.Sy NOTE
Some keys or values in configuration files can contain special characters like dollarsigns ($). To pass these types of vaiables to this utility, the dollar sign needs to be escaped with a slash (\\) or surrounded with single quates (').
.Pp
.Pp
.Sh  EXAMPLES
To list off some key/values in a config file.
.Bd -literal -offset indent
    syconf -f /path/config.file
.Ed
.Pp
To retrieve the value from a key in a file.
.Bd -literal -offset indent
    sysconf -f /path/config.file key
.Ed
.Pp
To change a value associated with a key.
.Bd -literal -offset indent
    sysconf -f /path/config.file key=value
.Ed
.Pp
To use a dollar sign in a key, escape it.
.Bd -literal -offset indent
    sysconf -f /path/config.file \\$key
.Ed
