name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build sysconf
      run: make
    
    - name: Run unit tests
      run: make test && ./test/test_sysconf
    
    - name: Run syntax tests
      run: chmod u+x ./test_syntax.sh && ./test_syntax.sh
